.TH spinach 1 "2011-10-16" "Spinach 0.4" "Spinach"
.SH NAME
spinach \- A small AUR helper written in Bash.
.SH SYNOPSIS
.B spinach
[options] [operation] [packages]
.SH DESCRIPTION
.B spinach
is a very tiny AUR helper written in Bash that will help you download, install, and update packages from the AUR.
.SH OPTIONS
.IP "--[no]ssl"
Use SSL when downloading packages and information from the AUR. This option has no effect on the pacman operations enabled with the '--rep' option.
.IP "--[no]col"
Use color in certian places.
.IP "--[no]rep"
Also use pacman for \fIsearch\fR, \fIprint\fR, and \fIinstall\fR operations. Searching will return results from both the AUR and official repositories. Printing information will return information from pacman if available and the AUR if not. Installing will install via the official repositories if found and attempt to install from the AUR otherwise.
.IP "--edit"
Specify the text editor to use in order to view the PKGBUILD and .install files when installing and upgrading packages. Defaults in this order if not specified: $EDITOR vim emacs vi nano most less more cat
.IP "--tmp"
If specified the spinach build and cache directories will be stored in spinach/ in this folder. If not specified, it will default to $TMPDIR if specified and as a last resort /tmp.
.IP "--max"
If specified this will be the max number of curl instances started to find out-of-date packages. If not specified, it defaults to 10. Note: the number of threads will actually be one more than this number assuming that there are at least that many packages to check.
.IP "--custom"
The absolute path to a directory full of custom PKGBUILDs (in sub directories with the package name) to use instead of ones in the AUR. One use of this is to use `spinach --custom ./ -i something' to install your version of something with dependencies from the AUR.
.IP "--needed"
When specified, AUR packages that are already installed on the computer will be skipped when trying to install them.
.SH COMMON OPERATIONS
.IP "-s"
Search for the specified package. A very similar option is '-sq' which prints only the package name from the search. This allows you to pipe the results to grep to do regex searching. See the EXAMPLES section. Results from '-s' will be sorted; results from '-sq' will not be.
.IP "-p"
Print information for the specified package.
.IP "-i"
Install the specified package.
.IP "-u"
Update packages found on the AUR. This will not update packages in the official repos or packages that have been deleted from the AUR.
.SH DO-IT-YOURSELF OPERATIONS
.IP "-d"
Download the specified package from the AUR and extract the tarball in the current directory.
.IP "-dd"
Download the specified package from the AUR and any AUR dependencies to the current directory.
.IP "-o"
List packages that are older than the one in the AUR.
.IP "-do"
Download all the AUR packages that are older than the one in the AUR to the current directory.
.SH CONFIG (optional)
.IP "UseSSL UseRepos UseColor"
Same as specifying --ssl, --rep, and --col.
.IP "Threads"
Same as specifying --max number
.IP "Temp"
Same as specifying --tmp dir
.IP "Editor"
Same as specifying --edit editor, overrides $EDITOR
.IP "Custom"
Same as specifying --custom dir
.SH NOTES
.IP "Does Not Ask for Password"
Newer versions of Spinach are intended to be able to install a bunch of packages easily. First it downloads all the files, then you are prompted to view them, then it installs depends, then it runs 'sudo -v' in the background every few seconds (if you have sudo), and finally compiles the applications. The key part of that sentence is: 'sudo -v' This will keep you from having to type in your password every time an application is compiled (since to compile applications, the depends normally have to be installed). To have this functionality enabled, install sudo. If you you have sudo and don't want it, email me and tell me why. Then I'll add an option to disable it.
.IP "View Files"
When you install packages using Spinach, you will be forced to type "y", return, "n", "y", return "n", etc. if you don't want to view the PKGBUILD and .install files. This is supposed to annoy you. It is for you safety. Read the PKGBUILD and .install files! They could easily delete your files if you don't.
.IP "Running as Root"
Never run Spinach as root. It will run makepkg as root which will run the PKGBUILD as root. You don't want that. There is nothing stopping you from running at root though. If you don't care about trashing your system, have fun running it as root.
.IP "No Internet"
If there is no Internet connection, Spinach probably won't print anything for most operations.
.IP "Version Control"
If you have some version-control package (-svn, -git, -hg, etc.) and you want to keep the trunk while updating, upgrade the package manually instead of using the automatic upgrade operation (-u). After installing an application (or upgrading) spinach will remove the files from the spinach/build/ directory.
.IP "Spinach Cache"
When you install or upgrade an application, the build directory in your temporary directory is deleted, but the generated package (if it was successfully created) will be copied to $Spintmpdir/spinach/cache/<bunch of text>.pkg.tar.xz. You can set the Spinach temp directory either in the config file or with the --tmp option.
.IP "Config versus Options"
Options specified (e.g. --ssl) will override whatever is in the config file (e.g. UseSSL).
.SH EXAMPLES
spinach -u
.TP
spinach --nossl -p package1 package2
.TP
source /usr/bin/spinach --col; aur_info spinach
.TP
spinach --col -dd $(spinach -sq openlp)
Download all AUR packages returned from a search.
.TP
spinach --rep -sq kernel | grep -E "26-(pf|ice|lts)$"
Regular expression searching
.SH AUTHOR
Garrett (http://floft.net/contact)
