.TH spinach 1 "2017-10-25" "Spinach 0.5" "Spinach"
.SH NAME
spinach \- Another AUR helper written in Bash.
.SH SYNOPSIS
.B spinach
[options] [operation] [packages]
.SH DESCRIPTION
.B spinach
is an AUR helper written in Bash that will help you download, install, and
update packages from the AUR. It started out small and grew. Now it's a bit
larger than I would like.
.SH OPTIONS
.IP "--[no]col"
Use color in certain places.
.IP "--[no]bat"
Run `sudo -v' in the background to keep you from having to type in your
password multiple times.
.IP "--[no]rep"
Also use pacman for the \fIinstall\fR operations. Installing will install via
the official repositories if found and attempt to install from the AUR
otherwise.
.IP "--edit"
Specify the text editor to use in order to view the PKGBUILD and .install files
when installing and upgrading packages. Defaults in this order if not
specified: $EDITOR vim emacs vi nano most less more cat
.IP "--tmp"
If specified the spinach build and cache directories will be stored in spinach/
in this folder. If not specified, it will default to $TMPDIR if specified and
as a last resort /tmp.
.IP "--max"
If specified this will be the max number of curl instances started to find
out-of-date packages. If not specified, it defaults to 10.
.IP "--custom"
The absolute path to a directory full of custom PKGBUILDs (in sub directories
with the package name) to use instead of ones in the AUR. One use of this is to
use `spinach --custom ./ -i something' to install your version of something
with dependencies from the AUR.
.IP "--needed"
When specified, AUR packages that are already installed on the computer will be
skipped when trying to install them.
.IP "--nocustom"
Don't ask to install or update, just do it. You won't have to view PKGBUILD or
install files, but you will probably have to type in your password for sudo
and correct PKGBUILD issues if it doesn't build.
.SH COMMON OPERATIONS
.IP "-s"
Search for the specified package. A very similar option is '-sq' which prints
only the package name from the search. This allows you to pipe the results to
grep to do regex searching. See the EXAMPLES section. Results from '-s' will be
sorted; results from '-sq' will not be. An asterisk after the name with '-s'
indicates an out-of-date package.
.IP "-p"
Print information for the specified package.
.IP "-i"
Install the specified package.
.IP "-u"
Update packages found on the AUR. This will not update packages in the official
repos or packages that have been deleted from the AUR.
.SH DO-IT-YOURSELF OPERATIONS
.IP "-d"
Download the specified package from the AUR and extract the tarball in the
current directory.
.IP "-dd"
Download the specified package from the AUR and any AUR dependencies to the
current directory.
.IP "-o"
List packages that are older than the one in the AUR.
.IP "-do"
Download all the AUR packages that are older than the one in the AUR to the
current directory.
.IP "--404"
List all the foreign packages installed that are not found in the AUR.
.SH CONFIG
The default system-wide configuration file is in /etc/spinach.conf. In a
multi-user environment, you can copy spinach.conf to ~/.config/spinach/config
which will override the system settings. Below are the available options for
the config file.
.IP "UseRepos=1 UseBatch=1 UseColor=1"
Same as specifying --rep, --bat, and --col.
.IP "UseRepos=0 UseBatch=0 UseColor=0"
Same as specifying --norep, --nobat, and --nocol.
.IP "Threads"
Same as specifying --max number
.IP "Temp"
Same as specifying --tmp dir
.IP "Editor"
Same as specifying --edit editor, overrides $EDITOR
.IP "Custom"
Same as specifying --custom dir
.SH NOTES
.IP "Does Not Ask for Password"
This is to allow for easily installing many packages at once. It downloads all
of the files, prompts you to view them, installs depends, runs 'sudo -v' in the
background every few seconds (you can disable this), and finally compiles the
packages. Running 'sudo -v' keeps you from having to type in your password. If
you don't disable this, you want to make sure that nothing in a PKGBUILD or
install file uses sudo.
.IP "Running as Root"
Never run Spinach as root. It will run makepkg as root which will run the
PKGBUILD as root.
.IP "No Internet"
Undefined behavior
.IP "Version Control"
If you have some version-control package (-svn, -git, -hg, etc.) and you want
to keep the trunk while updating, upgrade the package manually instead of using
the automatic upgrade operation (-u). After installing an application (or
upgrading) spinach will remove the files from the spinach/build/ directory.
.IP "Spinach Cache"
When you install or upgrade an application, the build directory in your
temporary directory is deleted, but the generated package (if it was
successfully created) will be copied to $Temp/spinach/cache/<...>.pkg.tar.xz.
You can set the Spinach Temp directory either in the config file or with the
--tmp option.
.IP "Config versus Options"
Options specified (e.g. --col) will override whatever is in the config file
(e.g. UseColor).
.IP "/tmp with noexec"
If you have your temporary directory TMPDIR mounted with noexec, you'll get
permission denied errors when running makepkg. Thus, you'll need to specify a
different tmp directory either with --tmp or in the config file.
.SH Security
.IP "Beware of sudo"
As mentioned, spinach will reset sudo's timeout every once in a while when
running in batch mode. You really need to watch out for anything running sudo
in a PKGBUILD or .install file. Spinach will print a warning if "sudo" is in
there, but it won't catch escaped, multi-line, or other obfuscations.
.IP "PKGBUILD Sourcing"
By default the PKGBUILD is not sourced. However, if it can't find .SRCINFO, it
will ask if you want to source it. If you say yes, code in the depends and
makedepends arrays will be somewhat sourced (after a bunch of grep and sed
calls to clean it up) before you even see it. If there is a way to execute code
other than with tick marks or $() syntax, then this may be an arbitrary code
execution vulnerability. (But, you can say "no" and look at it manually.)
.IP ".install files"
Spinach will warn if it sees that there is an install file and can't find it to
let you check, but if somehow "install=" is obfuscated in the PKGBUILD, it
won't display this warning.
.IP "--noconfirm"
Obviously this is a security issue. Only use this if you trust the PKGBUILD and
install files that will be executed.
.SH EXAMPLES
spinach --nocol -p package1 package2
.TP
spinach --col -dd $(spinach -sq openlp)
Download all AUR packages returned from a search.
.TP
spinach --rep -sq kernel | grep -E "26-(pf|ice|lts)$"
Regular expression searching
.SH AUTHOR
Garrett (http://floft.net/contact)
